use customer_behaviour_pattern;
SELECT * 

FROM customer
limit 10;

-- Q1 what is the total revenue generated by male and female..? --

SELECT gender,sum(purchase_amount) as total_revenue
FROM customer
GROUP BY gender;

-- Q2 which customer used a discount but still used more than the average purchase amount.? --

SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied=1 and purchase_amount >= (
SELECT avg(purchase_amount)
FROM customer);

-- Q3 which are the top 5 products with highest average ratings--

SELECT  item_purchased,round(avg(review_rating),2)
FROM customer
GROUP BY item_purchased
ORDER BY avg(review_rating) desc
limit 5;

-- Q4 Compare the average purchase amount between standard and express shipping--

SELECT shipping_type , round(avg(purchase_amount),2) as avg_purchase_amount
FROM customer

GROUP BY shipping_type
having shipping_type in ('Express','Standard');

-- Q5 Do subscribed customers spend more? compare average spend and total revenue between non subscriber and subscriber ?

SELECT subscription_status,count(customer_id),sum(purchase_amount) as total_spend,round(avg(purchase_amount),2) as average_spend
FROM customer
group by  subscrips;

 -- Q6 which 5 products have the highest percentage of purchases with  discount applied?

select item_purchased,
round(((sum(case when discount_applied=1 then 1 else 0 end)/count(*))*100),2 ) as dis_rate
from customer
group by item_purchased
order by dis_rate desc
limit 5 ;

-- Q7 Segment customer into new,returning and loyal based on there total numbers previous purchase and show the count of each segments--

with customer_type as (
select customer_id,previous_purchases,
CASE
WHEN previous_purchases=1 THEN 'New'
WHEN previous_purchases  between 2 and 10 THEN 'returning'
else 'loyal'
end as customer_segmentation
from customer )

SELECT customer_segmentation,count(*) as number_of_customer
FROM customer_type
group by customer_segmentation
order by number_of_customer ;

-- Q8 What are the top 3 most purchased products within the category--

with top_product as (
select category,item_purchased,count(customer_id),
row_number() over(partition by category order by count(customer_id) desc) as top_items
from customer
group by category,item_purchased

) 

select *
from top_product as t
where t.top_items < 4;

-- Q9 Are customer who are repeat buyer(more than 5 in previous purchase) are are likely to subscribe

select subscription_status,count(customer_id) as repeat_buyer
from customer
where previous_purchases >=5
group by subscription_status;


-- Q10 what is the revenue contribution of each age group--

select age_Group,sum(purchase_amount) as total_revenue
from customer
group by age_Group
order by total_revenue desc;
